### ISSUE TITLE
Allow injecting http client for metric pusher 

### ISSUE THREAD

**Issue by olehrechukh** [prom-client-net/prom-client-metricpusher#32]
Sometimes better solution is injecting http client.
For example, creating an http connection inside an Azure function is very expensive and not recommended.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0

**Comment by phnx47** [comment]
@olehrechukh Planned 👍🏻

**Comment by olehrechukh** [comment]
@phnx47 could I make pull requests?

**Comment by sanych-sun** [comment]
@olehrechukh You can fork the repository and create a [pull request from the fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by phnx47** [comment]
Published v2.2.0
